options:
  http-port:
    type: string
    default: '3000'
    description: HTTP port
  allow-custom-visualizations:
    type: boolean
    default: true
    description: Allow custom visualizations
  argo-archive-logs:
    type: boolean
    default: true
    description: Enable Argo log archive
  argo-key-format:
    type: string
    # Must have the same value as the default of `key-format` config in `argo-controller` charm.
    default: "artifacts/{{workflow.name}}/{{workflow.creationTimestamp.Y}}/{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}/{{pod.name}}"
    description: The keyFormat for pod logs artifacts stored
  disable-gke-metadata:
    type: boolean
    default: true
    description: Disable GKE metadata endpoint
  hide-sidenav:
    type: boolean
    default: true
    description: Hide navigation sidebar
