options:
  http-port:
    type: string
    default: '3000'
    description: HTTP port
  allow-custom-visualizations:
    type: boolean
    default: true
    description: Allow custom visualizations
  argo-archive-logs:
    type: boolean
    default: true
    description: Enable Argo log archive
  disable-gke-metadata:
    type: boolean
    default: true
    description: Disable GKE metadata endpoint
  hide-sidenav:
    type: boolean
    default: true
    description: Hide navigation sidebar
