import logging

from charmed_kubeflow_chisme.components import Component
from charmed_kubeflow_chisme.exceptions import GenericCharmRuntimeError
from charms.istio_beacon_k8s.v0.service_mesh import AppPolicy, ServiceMeshConsumer
from charms.istio_ingress_k8s.v0.istio_ingress_route import (
    BackendRef,
    HTTPPathMatch,
    HTTPRoute,
    HTTPRouteMatch,
    IstioIngressRouteConfig,
    IstioIngressRouteRequirer,
    Listener,
    PathModifier,
    PathModifierType,
    ProtocolType,
    URLRewriteFilter,
    URLRewriteSpec,
)
from ops import ActiveStatus

logger = logging.getLogger(__name__)


class AmbientIngressRequirerComponent(Component):
    """Component to manage the relations to Istio ambient."""

    def __init__(
        self,
        *args,
        service_name: str,
        port: int,
        path_prefix: str,
        url_rewrite: str,
        relation_name: str = "istio-ingress-route",
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        self.relation_name = relation_name
        self.service_name = service_name
        self.port = port
        self.path_prefix = path_prefix
        self.url_rewrite = url_rewrite

        self.ingress = IstioIngressRouteRequirer(
            self._charm,
            relation_name=self.relation_name,
        )

        self._config = self._get_ingress_config()

        self._mesh = ServiceMeshConsumer(self._charm)

    def _get_ingress_config(self):
        # Define listeners - names are auto-generated by the charm
        http_listener = Listener(port=80, protocol=ProtocolType.HTTP)

        config = IstioIngressRouteConfig(
            model=self._charm.model.name,  # Requirer's namespace where services live
            listeners=[http_listener],
            http_routes=[
                HTTPRoute(
                    name="http-route",
                    listener=http_listener,
                    matches=[HTTPRouteMatch(path=HTTPPathMatch(value=self.path_prefix))],
                    filters=[
                        URLRewriteFilter(
                            urlRewrite=URLRewriteSpec(
                                path=PathModifier(
                                    type=PathModifierType.ReplacePrefixMatch,
                                    value=self.url_rewrite,
                                )
                            )
                        )
                    ],
                    backends=[BackendRef(service=self.service_name, port=self.port)],
                ),
            ],
        )
        return config

    def _configure_app_leader(self, _):
        if self.ingress.is_ready():
            try:
                self.ingress.submit_config(self._config)
            except Exception as e:
                raise GenericCharmRuntimeError(f"Failed to submit ingress config: {e}")
        else:
            logger.debug("Ambient ingress relation not ready, skipping config submission.")

    def get_status(self):
        # This component depends on LeadershipGateComponent so no need to check for leadership here
        # If ingress config failed, the `_configure_app_leader` method raises an error
        # Otherwise simply return ActiveStatus()
        return ActiveStatus()
