
# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:

jobs:
  quality-checks:
    name: Quality Checks
    strategy:
      matrix:
        charm:
          - kfp-api
          - kfp-persistence
          - kfp-profile-controller
          - kfp-schedwf
          - kfp-ui
          - kfp-viewer
          - kfp-viz
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@all
    with:
      charm-path: ./charms/${{ matrix.charm }}
      charm-name: ${{ matrix.charm }}

  unit-tests:
    name: Unit Tests
    strategy:
      matrix:
        charm:
          - kfp-api
          - kfp-persistence
          - kfp-profile-controller
          - kfp-schedwf
          - kfp-ui
          - kfp-viewer
          - kfp-viz
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_unit-tests.yaml@all
    secrets: inherit
    with:
      charm-name: ${{ matrix.charm }}

  integration-tests:
    name: Integration Tests
    needs: quality-checks
    strategy:
      matrix:
        charm:
          - kfp-api
          - kfp-profile-controller
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_integration-tests.yaml@all
    secrets: inherit
    with:
      charm-name: ${{ matrix.charm }}

  bundle-tests:
    name: Bundle Tests
    needs: quality-checks
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_bundle.yaml@all
    with:
      charm-name: ${{ inputs.charm-name }}