# On pull_request, we:
# * always run tests
# * always publish to Charmhub at latest/edge/PR-<number>

name: On Pull Request

on:
  pull_request:

jobs:
  tests:
    name: CI
    uses: ./.github/workflows/_ci.yaml

  publish:
    name: Publish
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_publish.yaml@all
    secrets: inherit
