name: On Push

# On push to main or track/** branch, we:
# * always publish to Charmhub at latest/edge/PR-<number>
# * always run tests

on:
  push:
    branches:
    - main
    - track/**

jobs:
  on-push:
    strategy:
      matrix:
        charm:
          - kfp-api
          - kfp-persistence
          - kfp-profile-controller
          - kfp-schedwf
          - kfp-ui
          - kfp-viewer
          - kfp-viz
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/push-template.yaml@all
    secrets: inherit
    with:
      charm-path: ./charms/${{ matrix.charm }}
      charm-name: ${{ matrix.charm }}
      run-bundle: true
