name: On Pull Request

# On pull_request, we:
# * always publish to Charmhub at latest/edge/PR-<number>
# * always run tests

on:
  pull_request:

jobs:
  pull-request:
    strategy:
      matrix:
        charm:
          - kfp-api
          - kfp-persistence
          - kfp-profile-controller
          - kfp-schedwf
          - kfp-ui
          - kfp-viewer
          - kfp-viz
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/pull-request-template.yaml@all
    secrets: inherit
    with:
      charm-path: ./charms/${{ matrix.charm }}
      charm-name: ${{ matrix.charm }}
      run-bundle: true
