name: On Pull Request

# On pull_request, we:
# * always publish to Charmhub at latest/edge/PR-<number>
# * always run tests

on:
  pull_request:

jobs:
  tests:
    name: CI
    uses: ./.github/workflows/_ci.yaml

  publish:
    name: Publish
    needs: quality-checks
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_publish.yaml@all
