# On push to main or track/** branch, we:
# * always run tests
# * publish to Charmhub at latest/edge/PR-<number> if tests pass

name: On Push

on:
  push:
    branches:
    - main
    - track/**


jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/_ci.yaml

  # publish runs in series with tests, and only publishes if tests passes
  publish:
    name: Publish
    needs: tests
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_publish.yaml@all
    secrets: inherit
