name: On Pull Request

# On pull_request, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# * always run builds with cache
on:
  pull_request:

jobs:
  get-charm-paths:
    name: Generate the Charm Matrix content
    runs-on: ubuntu-latest
    outputs:
      charm-paths: ${{ steps.get-charm-paths.outputs.charm-paths }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get paths for all charms in this repo
        id: get-charm-paths
        uses: canonical/kubeflow-ci/actions/get-charm-paths@main

  build:
    strategy:
      matrix:
        charm: ${{ fromJSON(needs.get-charm-paths.outputs.charm-paths) }}
    name: Build charm | ${{ matrix.charm }}
    needs:
      - get-charm-paths
    with:
      charmcraft-snap-channel: latest/candidate  # TODO: remove after charmcraft 3.3 stable release
      path-to-charm-directory: ${{ matrix.charm }}

  tests:
    name: Run Tests
    needs: build
    uses: ./.github/workflows/integrate.yaml
    secrets: inherit
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}

  # publish runs in parallel with tests, as we always publish in this situation
  publish-charm:
    name: Publish Charm
    needs: build
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
