name: On Pull Request

# On pull_request, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests

on:
  pull_request:

jobs:
  on_pull_request:
    name: Build, test, publish
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/pull-request-template.yaml@main
