name: On Pull Request

# On pull_request, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# * always run builds with cache
on:
  pull_request:

jobs:
  get-charm-paths:
    name: Generate the Charm Matrix content
    runs-on: ubuntu-latest
    outputs:
      charm_paths: ${{ steps.get-charm-paths.outputs.charm-paths }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get paths for all charms in this repo
        id: get-charm-paths
        uses: canonical/kubeflow-ci/actions/get-charm-paths@main

  build:
    name: Build charms
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v29.0.1
    needs: get-charm-paths
    strategy:
      matrix:
        charm: ${{ fromJson(needs.get-charm-paths.outputs.charm_paths) }}
    with:
      # Update to 3.x/stable once the latest/candidate is released to that track
      charmcraft-snap-channel: latest/candidate
      path-to-charm-directory: ${{ matrix.charm }}

  tests:
    name: Run Tests
    needs: build
    uses: ./.github/workflows/integrate.yaml
    secrets: inherit

  # publish runs in parallel with tests, as we always publish in this situation
  publish-charm:
    name: Publish Charm
    needs: build
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
